/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.client.presentation;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author juan jose
 */
public class GUILoginUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GUILoginUsuario
     */
    public GUILoginUsuario() {
        initComponents();
        showImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        RBtnAdmin1 = new javax.swing.JRadioButton();
        LblTitulo = new javax.swing.JLabel();
        PnlLoginUsuario = new javax.swing.JPanel();
        LblAplicacion = new javax.swing.JLabel();
        LblDeseaIngresar = new javax.swing.JLabel();
        RBtnAdmin = new javax.swing.JRadioButton();
        BtnIngresar = new javax.swing.JButton();
        RBtnCliente = new javax.swing.JRadioButton();
        lblImgPrincipal = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        RBtnAdmin1.setBackground(new java.awt.Color(102, 153, 255));
        RBtnAdmin1.setText("Administrador");
        RBtnAdmin1.setName("RadioBtnAdmin"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo.setText("Software Food");
        LblTitulo.setName("JLabelTItulo"); // NOI18N
        getContentPane().add(LblTitulo, java.awt.BorderLayout.PAGE_START);

        PnlLoginUsuario.setBackground(new java.awt.Color(51, 153, 255));
        PnlLoginUsuario.setName("JPanelLogo"); // NOI18N

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("    Aplicación Software Food");
        LblAplicacion.setName("JLabelTitulo2"); // NOI18N

        LblDeseaIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblDeseaIngresar.setText("Desea ingresar como:");
        LblDeseaIngresar.setName("JLabelDeseaIngresar"); // NOI18N

        RBtnAdmin.setBackground(new java.awt.Color(102, 153, 255));
        RBtnAdmin.setText("Administrador");
        RBtnAdmin.setName("RadioBtnAdmin"); // NOI18N

        BtnIngresar.setText("Ingresar");
        BtnIngresar.setName("BtnIngresar"); // NOI18N
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        RBtnCliente.setBackground(new java.awt.Color(102, 153, 255));
        RBtnCliente.setText("Cliente");
        RBtnCliente.setName("RBtnCliente"); // NOI18N

        lblImgPrincipal.setText("imagenPirncipal");

        javax.swing.GroupLayout PnlLoginUsuarioLayout = new javax.swing.GroupLayout(PnlLoginUsuario);
        PnlLoginUsuario.setLayout(PnlLoginUsuarioLayout);
        PnlLoginUsuarioLayout.setHorizontalGroup(
            PnlLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginUsuarioLayout.createSequentialGroup()
                .addGroup(PnlLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LblAplicacion)
                        .addGroup(PnlLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlLoginUsuarioLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblImgPrincipal))
                            .addGroup(PnlLoginUsuarioLayout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(RBtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlLoginUsuarioLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(LblDeseaIngresar)
                                .addGap(18, 18, 18)
                                .addComponent(RBtnAdmin))))
                    .addGroup(PnlLoginUsuarioLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        PnlLoginUsuarioLayout.setVerticalGroup(
            PnlLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblImgPrincipal)
                .addGap(15, 15, 15)
                .addComponent(LblAplicacion)
                .addGap(41, 41, 41)
                .addGroup(PnlLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDeseaIngresar)
                    .addComponent(RBtnAdmin))
                .addGap(18, 18, 18)
                .addComponent(RBtnCliente)
                .addGap(26, 26, 26)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(PnlLoginUsuario, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
        if (RBtnAdmin.isSelected() == true) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    GUILoginAdmin ins = new GUILoginAdmin();
                    //ins.setExtendedState(MAXIMIZED_BOTH);
                    ins.setVisible(true);
                    setVisible(false);
                }
            });
        } else if (RBtnCliente.isSelected() == true) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    setVisible(false);
                    GUILoginCliente ins = new GUILoginCliente();
                    //ins.setExtendedState(MAXIMIZED_BOTH);
                    ins.setVisible(true);
                    setVisible(false);
                }
            });
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void showImage() {
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(15, 5, 90, 90);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH)));
        PnlLoginUsuario.add(lblImgPrincipal);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("resources/Icono_SoftwareFood.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILoginUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblDeseaIngresar;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlLoginUsuario;
    private javax.swing.JRadioButton RBtnAdmin;
    private javax.swing.JRadioButton RBtnAdmin1;
    private javax.swing.JRadioButton RBtnCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImgPrincipal;
    // End of variables declaration//GEN-END:variables
}
