/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.client.access.IClientAccess;
import co.unicauca.restaurant.client.domain.ClientService;
import co.unicauca.restaurant.commons.domain.Component;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author juan jose
 */
public class GUIListarComponentes extends javax.swing.JFrame {

    IClientAccess service;
    
    DefaultListModel modelListComponentes;
    
    /**
     * Creates new form GUIListarComponentes
     */
    public GUIListarComponentes() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        this.modelListComponentes = new DefaultListModel();
        ListComponentes.setModel(modelListComponentes);
        this.service = Factory.getInstance().getClienteService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlListarComponentes = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblListarComponentes = new javax.swing.JLabel();
        SPnListarComponentes = new javax.swing.JScrollPane();
        ListComponentes = new javax.swing.JList<>();
        BtnListarComponentes = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlListarComponentes.setBackground(new java.awt.Color(51, 153, 255));

        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblListarComponentes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblListarComponentes.setText("Listar Componentes Almuerzo Ejecutivo");

        SPnListarComponentes.setViewportView(ListComponentes);

        BtnListarComponentes.setText("Listar componentes");
        BtnListarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarComponentesActionPerformed(evt);
            }
        });

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        lblImgPrincipal.setText("ImgPrincipal");

        javax.swing.GroupLayout PnlListarComponentesLayout = new javax.swing.GroupLayout(PnlListarComponentes);
        PnlListarComponentes.setLayout(PnlListarComponentesLayout);
        PnlListarComponentesLayout.setHorizontalGroup(
            PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAtras)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlListarComponentesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnListarComponentes)
                .addGap(179, 179, 179))
            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(SPnListarComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblListarComponentes)
                            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                                .addComponent(lblImgPrincipal)
                                .addGap(85, 85, 85)
                                .addComponent(LblAplicacion)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        PnlListarComponentesLayout.setVerticalGroup(
            PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)
                        .addGap(5, 5, 5)
                        .addComponent(LblAplicacion))
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblImgPrincipal)))
                .addGap(18, 18, 18)
                .addComponent(LblListarComponentes)
                .addGap(18, 18, 18)
                .addComponent(SPnListarComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnListarComponentes)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        getContentPane().add(PnlListarComponentes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUIOpcionesAdmin ins = new GUIOpcionesAdmin();
        ins.setVisible(true); 
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnListarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarComponentesActionPerformed
        try {
            listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnListarComponentesActionPerformed
    
    
    public void listar() throws Exception {
        ClientService servicioRestaurante = new ClientService(service);
        int idComp = 1;
        List<Component> lsComponente = servicioRestaurante.listarComponents();
        if (lsComponente.size() > 0) {
            modelListComponentes.removeAllElements();
            for (Component ls : lsComponente) {
                modelListComponentes.addElement("ID: " + ls.getCompID()+ " NOMBRE: " + ls.getCompNombre()
                        + " TIPO: " + ls.getCompTipo());
            }
        }
    }
    
    private void showImage() {
        
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80,Image.SCALE_SMOOTH)));
        PnlListarComponentes.add(lblImgPrincipal);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnListarComponentes;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblListarComponentes;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JList<String> ListComponentes;
    private javax.swing.JPanel PnlListarComponentes;
    private javax.swing.JScrollPane SPnListarComponentes;
    private javax.swing.JLabel lblImgPrincipal;
    // End of variables declaration//GEN-END:variables
}
