/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.client.access.IClientAccess;
import co.unicauca.restaurant.client.domain.ClientService;
import co.unicauca.restaurant.commons.domain.Component;
import co.unicauca.restaurant.commons.domain.Restaurant;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author juan jose
 */
public class GUIListarRestaurantes extends javax.swing.JFrame {

    IClientAccess service;
    
    DefaultListModel modelListCoRestaurantes;
    /**
     * Creates new form GUIListarRestaurantes
     */
    public GUIListarRestaurantes() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        this.modelListCoRestaurantes = new DefaultListModel();
        ListRestaurantes.setModel(modelListCoRestaurantes);
        this.service = Factory.getInstance().getClienteService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListComponentes = new javax.swing.JList<>();
        PnlListarRestaurantes = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblVerRestaurantes = new javax.swing.JLabel();
        BtnVerRestaurantes = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        btnSelecRestaurat = new javax.swing.JButton();
        ListRestaurantes = new javax.swing.JList<>();
        lblImgPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlListarRestaurantes.setBackground(new java.awt.Color(51, 153, 255));

        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblVerRestaurantes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblVerRestaurantes.setText("Visualizar los restaurantes que tiene la ciudad");

        BtnVerRestaurantes.setText("Visualizar Restaurantes");
        BtnVerRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerRestaurantesActionPerformed(evt);
            }
        });

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        btnSelecRestaurat.setText("Seleccionar Restaurante");
        btnSelecRestaurat.setName("btnSelecRestaurat"); // NOI18N
        btnSelecRestaurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecRestauratActionPerformed(evt);
            }
        });

        lblImgPrincipal.setText("ImgPrincipal");

        javax.swing.GroupLayout PnlListarRestaurantesLayout = new javax.swing.GroupLayout(PnlListarRestaurantes);
        PnlListarRestaurantes.setLayout(PnlListarRestaurantesLayout);
        PnlListarRestaurantesLayout.setHorizontalGroup(
            PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblImgPrincipal)
                        .addGap(99, 99, 99)
                        .addComponent(LblAplicacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAtras))
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(LblVerRestaurantes))
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(BtnVerRestaurantes))
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ListRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnSelecRestaurat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlListarRestaurantesLayout.setVerticalGroup(
            PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitulo)
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblImgPrincipal)))
                        .addGap(27, 27, 27))
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblAplicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LblVerRestaurantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnVerRestaurantes)
                .addGap(18, 18, 18)
                .addComponent(ListRestaurantes, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelecRestaurat)
                .addGap(37, 37, 37))
        );

        getContentPane().add(PnlListarRestaurantes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecRestauratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecRestauratActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GUISeleccionarRestaurante ins = new GUISeleccionarRestaurante();
        ins.setVisible(true); 
    }//GEN-LAST:event_btnSelecRestauratActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUIOpcionesCliente ins = new GUIOpcionesCliente();
        ins.setVisible(true); 
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnVerRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerRestaurantesActionPerformed
        try {
            listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnVerRestaurantesActionPerformed
    
    public void listar() throws Exception {
        ClientService servicioRestaurante = new ClientService(service);
        int idComp = 1;
        List<Restaurant> lsRestaurante= servicioRestaurante.listarRestaurants();
        this.AllRestaurants = lsRestaurante;
        if (lsRestaurante.size() > 0) {
            modelListCoRestaurantes.removeAllElements();
            for (Restaurant ls : lsRestaurante) {
                modelListCoRestaurantes.addElement("NIT: " + ls.getNit()+ " Admin_ID: " + ls.getCli_Id().getCus_id()
                        + " Nombre: " + ls.getNombre()+ " Direccion: " + ls.getRes_Direccion());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarRestaurantes().setVisible(true);
            }
        });
    }
    
    private List<Restaurant> AllRestaurants = null;
    
    public List<Restaurant> GetRestaurants(){
        try {
            listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return AllRestaurants;
    }
    
    private void showImage() {
        
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80,Image.SCALE_SMOOTH)));
        PnlListarRestaurantes.add(lblImgPrincipal);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnVerRestaurantes;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblVerRestaurantes;
    private javax.swing.JList<String> ListComponentes;
    private javax.swing.JList<String> ListRestaurantes;
    private javax.swing.JPanel PnlListarRestaurantes;
    private javax.swing.JButton btnSelecRestaurat;
    private javax.swing.JLabel lblImgPrincipal;
    // End of variables declaration//GEN-END:variables
}
