/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.client.presentation;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author juan jose
 */
public class GUILoginCliente extends javax.swing.JFrame {

    /**
     * Creates new form GUILoginCliente
     */
    public GUILoginCliente() {
        initComponents();
        showImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlLoginCliente = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblLoginCliente = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        LblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlLoginCliente.setBackground(new java.awt.Color(51, 153, 255));

        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblLoginCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblLoginCliente.setText("Login del Cliente");

        LblUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblUsuario.setText("Usuario:");

        LblContrasenia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblContrasenia.setText("Contrasenia:");

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        lblImgPrincipal.setText("ImgPrincipal");

        javax.swing.GroupLayout PnlLoginClienteLayout = new javax.swing.GroupLayout(PnlLoginCliente);
        PnlLoginCliente.setLayout(PnlLoginClienteLayout);
        PnlLoginClienteLayout.setHorizontalGroup(
            PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                        .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(LblLoginCliente))
                            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblAplicacion)
                                    .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                                            .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(LblContrasenia)
                                                .addComponent(LblUsuario))
                                            .addGap(18, 18, 18)
                                            .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                                .addComponent(txtContrasenia)))))))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                        .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblImgPrincipal))
                            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LblTitulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAtras)))
                .addContainerGap())
        );
        PnlLoginClienteLayout.setVerticalGroup(
            PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)
                        .addGap(136, 136, 136)
                        .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImgPrincipal)
                        .addGap(8, 8, 8)
                        .addGroup(PnlLoginClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnlLoginClienteLayout.createSequentialGroup()
                                .addComponent(LblAplicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblLoginCliente)
                                .addGap(40, 40, 40)
                                .addComponent(LblUsuario))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LblContrasenia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        getContentPane().add(PnlLoginCliente, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
        String usuario;
        String contrasenia;
        usuario = txtUsuario.toString();
        contrasenia = txtContrasenia.toString(); 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    JOptionPane.showMessageDialog(null, "Validacion del cliente en construcción!!!");
                    GUIOpcionesCliente ins = new GUIOpcionesCliente();
                    ins.setVisible(true);
                    setVisible(false);
                }
            });
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUILoginUsuario ins = new GUILoginUsuario();
        ins.setVisible(true);
    }//GEN-LAST:event_BtnAtrasActionPerformed
    
    private void showImage() {
        
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80,Image.SCALE_SMOOTH)));
        PnlLoginCliente.add(lblImgPrincipal);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILoginCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblContrasenia;
    private javax.swing.JLabel LblLoginCliente;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JPanel PnlLoginCliente;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
