/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.client.access.IClientAccess;
import co.unicauca.restaurant.client.domain.ClientService;
import co.unicauca.restaurant.commons.domain.Customer;
import java.awt.Image;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author juan jose
 */
public class GUILoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GUILoginAdmin
     */
    public GUILoginAdmin() {
        initComponents();
        showImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlLoginAdmin = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblLoginAdmin = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        LblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlLoginAdmin.setBackground(new java.awt.Color(51, 153, 255));

        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblLoginAdmin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblLoginAdmin.setText("Login del Administrador");

        LblUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblUsuario.setText("Usuario:");

        LblContrasenia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblContrasenia.setText("Contrasenia:");

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        lblImgPrincipal.setText("ImgPrincipal");

        javax.swing.GroupLayout PnlLoginAdminLayout = new javax.swing.GroupLayout(PnlLoginAdmin);
        PnlLoginAdmin.setLayout(PnlLoginAdminLayout);
        PnlLoginAdminLayout.setHorizontalGroup(
            PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAtras))
                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                        .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(LblLoginAdmin))
                            .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblImgPrincipal)
                                .addGap(80, 80, 80)
                                .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                                        .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LblContrasenia)
                                            .addComponent(LblUsuario))
                                        .addGap(18, 18, 18)
                                        .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                            .addComponent(txtContrasenia)))
                                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(LblAplicacion)))))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlLoginAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        PnlLoginAdminLayout.setVerticalGroup(
            PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImgPrincipal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                                .addComponent(LblAplicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlLoginAdminLayout.createSequentialGroup()
                                        .addComponent(LblLoginAdmin)
                                        .addGap(48, 48, 48)
                                        .addComponent(LblUsuario)))))
                        .addGap(18, 18, 18)
                        .addComponent(LblContrasenia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        getContentPane().add(PnlLoginAdmin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String usuario;
        String contrasenia;
        usuario = txtUsuario.getText();
        contrasenia = txtContrasenia.getText();

        if (validarAdministrador(usuario, contrasenia) == true) {
            System.out.println("ENTRO A LA VALIDACION FINAL");
            setVisible(false);
            GUIOpcionesAdmin ins = new GUIOpcionesAdmin();
            ins.getUsuario(usuario);
            ins.setVisible(true);
            
            txtUsuario.setText("");
            txtContrasenia.setText("");
        }
        
    }                                           
//GEN-LAST:event_BtnIngresarActionPerformed

    boolean validarAdministrador(String usuario, String contrasenia) {
        IClientAccess service = Factory.getInstance().getClienteService();
        ClientService servicioRestaurante = new ClientService(service);

        Customer cliente = null;
        List<Customer> lsDia = null;
        try {
            lsDia = servicioRestaurante.findCustomer();
            if (lsDia.size() > 0) {
                for (Iterator<Customer> iterator = lsDia.iterator(); iterator.hasNext();) {
                    Customer next = iterator.next();
                    // System.out.println(next.getCus_id() + " - " + next.getCus_nombre());
                    if (String.valueOf(next.getCus_id()).equals(usuario)) {
                        cliente = new Customer(next.getCus_id(), next.getCus_nombre(), next.getCus_direccion(), next.getCus_password(), next.getCus_Telefono(), next.getCus_tipo());
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Error al hacer la consulta ");
        }

        if (cliente != null) {
            if (contrasenia.equals(cliente.getCus_password())) {
                return true;
            }else{
                JOptionPane.showMessageDialog(null,"  Contraseña Incorrecta");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usuatio " + usuario + "  Incorrecto, o no registrado");
            return false;
        }
        return false;
    }
    
    private void showImage() {
        
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80,Image.SCALE_SMOOTH)));
        PnlLoginAdmin.add(lblImgPrincipal);
        
    }
    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUILoginUsuario ins = new GUILoginUsuario();
        ins.setVisible(true);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblContrasenia;
    private javax.swing.JLabel LblLoginAdmin;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JPanel PnlLoginAdmin;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
